blank_issues_enabled: false
contact_links:
  - name: 📧 Soporte TI – SLEP Colchagua
    url: mailto:soporte.ti@slepcolchagua.cl
    about: Si tienes problemas con el acceso o sugerencias generales, contáctanos por correo.
